version: '24.0'

networks:
  web:
    external: true

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ../.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "dbprod:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - web

  php: 
    build:
      context: ../
      dockerfile: php.dockerfile
    restart: unless-stopped
    volumes:
      - ../:/var/www/html:delegated
    ports:
      - "81:80"
    depends_on:
      - mysql
    networks:
      - web

  wp:
    build:
      context: ../
      dockerfile: php.dockerfile
    volumes:
      - ../:/var/www/html:delegated
    entrypoint: ["wp", "--allow-root"]
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: ../.env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - web

volumes:
  dbprod: